---
title: "Aula 10"
author: "Gustavo Dutra"
date: "2025-04-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exemplo 2 - web scraping

```{r, include = FALSE}

library(rvest)
library(tidyverse)
library(dplyr)
library(stringr)

url <- "https://www.bbc.com/"
page <- read_html(url)

headline <- page %>%
  html_nodes(".eywmDE") %>%
  html_text()

headline <- data.frame(manchete = headline) %>%
  arrange(manchete) %>%
  distinct()

headline <- headline %>%
  mutate(manchete = str_replace_all(manchete, "^['’]+", "")) %>%
  arrange(manchete) %>%
  distinct()

```

Vejam as 10 últimas manchetes do dia em ordem alfabética:

```{r, echo = FALSE}

knitr::kable(tail(headline, n = 10))
```

Agora, vamos obter os temas das notícias.
O seletor de gadget indicou que o elemento CSS que inseri os temas é o elemento **.gwNQGk**.

```{r}
titles <- page %>%
  html_nodes(".gwNQGk") %>%
  html_text()

titles <- data.frame(Temas = titles)

# Limpar o texto referente ao tempo de postagem
titles$Temas <- sub(".*?ago", "", titles$Temas)

titles <- titles %>%
  arrange(Temas)

# Limpar temas de outras datas
titles$Temas <- sub(".*?2024", "", titles$Temas)
titles$Temas <- sub(".*?2025", "", titles$Temas)

titles <- titles %>%
  arrange(Temas)

# Eliminar linhas vazias
titles <- titles %>%
  filter(Temas != "")

tabela <- table(titles)
tabela <- data.frame(tabela)
```



