---
title: "Aula 10"
author: "Gustavo Dutra"
date: "2025-04-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exemplo 2 - web scraping

```{r, include = FALSE}

library(rvest)
library(tidyverse)

url = "https://www.bbc.com/"
  
page = read_html(url)

headline = page %>%
  	html_nodes(c(".eywmDE")) %>%
  	html_text()

headline = data.frame(headline) %>%
  rename(manchete = headline) %>%
  arrange(manchete) %>%
  unique() # remove as duplicatas

 library(dplyr)
 library(stringr)

 headline = headline %>%
  	mutate(Manchete_ordenada = str_replace_all(manchete, "^['’]+", "")) %>%
  	arrange(Manchete_ordenada) %>%
 	  select(-Manchete_ordenada) %>%
  	unique()

```

Vejam as 10 últimas manchetes do dia em ordem alfabética:

```{r, echo = FALSE}

knitr::kable(tail(headline, n = 10))
```

Agora, vamos obter os temas das notícias.
O seletor de gadget indicou que o elemento CSS que inseri os temas é o elemento **.gwNQGk**.

```{r}
 titles = page %>%
  	html_nodes(c(".gwNQGk")) %>%
  	html_text()

 titles = data.frame(Temas = titles) 
 
 # Vamos limpar o texto referente ao tempo de postagem
 titles$Temas = sub(".*?ago", "", titles$Temas)
 
 titles = titles %>%
   arrange(Temas)
 
 # Precisamos limpar os temas que são de outras datas
 titles$Temas = sub(".*?2024", "", titles$Temas)
 titles$Temas = sub(".*?2025", "", titles$Temas)
 
  titles = titles %>%
   arrange(Temas)
 # Agora precisamos eliminar as linhas vazias
  titles <- titles %>%
  	filter(Temas != "") 
  
  tabela = table(titles)
  tabela = data.frame(tabela)
  
```



