---
title: "Aula14"
output: html_document
---
```
{r setup, include=FALSE}
knitr ::opts_chunk$set(echo=TRUE)
```


##Revisão de regressão linear simples

a) construa o diagrama de dispersão entre SAC (complaint handling) e confiança (trust).
```
{r, echo= FALSE, warning=FALSE,message=FALSE}
setwd("~/ProgramaçãoR")
#leitura da base
library(readxl)
dados= read_excel("Aula 07 - regressão simples.xlsx",
                  sheet= "TV por assinatura")


#construir o diagrama de dispersão
#x=sac e que y = confiança

library(ggplot2)
ggplot(dados, aes(x= SAC, y= CONFIANÇA))+
  geom_point()
```




#sempre que os dados vierem de alguma variável com escal Likert, pode haver muita sobreposição. Uma forma de resolver é usar a gemetria jitter.

```
{r}
set.seed(7)
ggplot(dados, aes(x= SAC, y= CONFIANÇA))+
  geom_jitter(alpha= 0.2) +
  geom_smooth(method = "lm")
```

#A geometria smooth com método "lm"- linear model, serve para indicar qual seria o possivel modelo de regressão para esses dados.

```
{r}
set.seed(7)
ggplot(dados, aes(x= SAC, y= CONFIANÇA))+
  geom_point(alpha= 0.4)
```

#Outra forma de resolver a quetsão da sobreposição é usar o parametro alpha dentro geometria point. Ele serve para deixar o ponto transparente

#O diagrama mostra que aqueles que deram notas mais alta para SAC , confiam mais no proveador de TV por assinatura



#b) Calcule a correlação e analise-a

```
{r, echo=FALSE, warning=FALSE,message=FALSE}
x= dados$SAC
y= dados$CONFIANÇA
```

#Afunção cor calcula a correlação entre as variáveis 

round(cor(x,y),2)



#o sinal positivo indica que as variáveis são diretamente proporcionais e o módulo entre 0.30<= |r| < 0.70 indica que o efeito da nota dada ao SAC na confiança é moderado.


c) Encontre a equação de regressão e interprete a inclinação da reta
```
{r}
# O código para a obtenção da equação está no slide 15.

 modelo = lm(y ~ x) 
 resumo = summary(modelo)

 # Para obter os coeficientes com duas casas decimais
 tabela1= round(resumo$coefficients,2) 

 # Para obter os LI e LS dos coeficientes com duas casas decimais
 tabela2=round(confint(modelo, level = 0.95),2) 
 
 library(knitr)
 kable(tabela1, caption = "Resultados da regressão")
 kable(tabela2, caption = "Variação dos  coeficientes")
```



#Na coluna estimate, aparecem os coeficientes do modelo de regressão. A equação é 
$$ Confiança = 1.40 + 0.59*SAC.$$

#Os valores dos coeficientes na equação são os valores médios (cenário realista).

A tabela de variação (tabela 2) mostra os cénarios pessimista e otimista.

A nota mínima dada confiança quando a nota do SAc pudesse ser igual a zero é 1.04 e a nota máxima, 1.76 com 95% de confiança.


#Estime a confiança de um consumidor que dá nota 2 ao serviço de atendimento ao consumidor.

```
{r}
# Previsão intervalar no modelo

xp = 2

newdata = data.frame(x = c( xp)) # Insira o valor desejado de x no lugar de xp

tabela3= predict(modelo, newdata, interval = "confidence", level= 0.95
```

 # Ajustar o nível de confiança para o valor desejado.
kable(round(tabela3 , 2), caption ="Previsão")



#A previsão possui os três cenários: fit (realista), lwr= lower (pessimista) e upr= upper (otimista)


Exercicio- Construa um dashboard com o diagrama de dispersão que relaciona as variáveis SATISFAÇÃO e INTENÇÃO. No dashboard, devem aparecer as tabelas com a equação e os intervalos de variação e o diagrama com a ferramenta plotly.

{r}
